---
- name: Install and configure tomcat
  hosts: all
  gather_facts: false
  become: yes 
  tasks:
    - name: Copy file tomcat.service
      copy:
        src: /root/ansible/tomcat.service
        dest: /etc/systemd/system/tomcat.service
#    - name: Starting tomcat
#      shell: nohup /usr/local/latest/bin/startup.sh &

