---
- name: Install and configure tomcat
  hosts: all
  gather_facts: false
  become: yes 
  tasks:
    - name: repo update
      yum:
        name: "*"
        state: latest
    - name: Installing required java
      yum:
        name: java-1.8.0-openjdk
        state: present
    - name: Setting default java
      alternatives:
        name: java 
        link: /usr/bin/java
        path: /usr/lib/jvm/jre-1.8.0-openjdk/bin/java
    - name: Downloading required tomcat
      get_url: 
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.40/bin/apache-tomcat-9.0.40.tar.gz
        dest: /usr/local
    - name: Extracting downloaded tomcat
      unarchive:
        src: "/usr/local/apache-tomcat-9.0.40.tar.gz"
        dest: /usr/local
        remote_src: yes
    - name: Renaming tomcat home
      command: mv /usr/local/apache-tomcat-9.0.40 /usr/local/latest
    - name: Criar grupo tomcat
      command: groupadd tomcat
    - name: Criar usuário tomcat
      command: useradd -M -s /bin/nologin -g tomcat -d /usr/local/latest/ tomcat
    - name: Propriedade diretorio ao grupo tomcat
      command: chgrp -R tomcat /usr/local/latest/
    - name: 1 Permissao diretorio conf
      command: chmod -R g+r /usr/local/latest/conf
    - name: 2 Permissao diretorio conf
      command: chmod g+x /usr/local/latest/conf
    - name: Propriedade pasta webapps
      command: chown -R tomcat /usr/local/latest/webapps/
    - name: Propriedade pasta work
      command: chown -R tomcat /usr/local/latest/work/
    - name: Propriedade pasta temp
      command: chown -R tomcat /usr/local/latest/temp/
    - name: Propriedade pasta logs
      command: chown -R tomcat /usr/local/latest/logs
    - name: Copy file tomcat.service
      copy:
        src: /root/ansible/tomcat.service
        dest: /etc/systemd/system/tomcat.service
    - name: Recarregar o Systemd
      command: systemctl daemon-reload
    - name: Iniciar servico tomcat
      command: systemctl start tomcat.service
    - name: Habilitar servico tomcat
      command: systemctl enable tomcat.service
    - name: Abrir porta 8080
      command: firewall-cmd --zone=public --add-port=8080/tcp
#    - name: Starting tomcat
#      shell: nohup /usr/local/latest/bin/startup.sh &

